# Generated by Django 5.0.4 on 2024-06-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Other_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Votes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='voters',
            fields=[
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Other_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Form', models.IntegerField()),
                ('Index_Number', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Token', models.CharField(max_length=8, unique=True)),
                ('is_token_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'voters',
            },
        ),
    ]
